server:
  port: 8222  # Port on which the API Gateway will run

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nonfunctional_message
          uri: lb://nonfunctionalmessage
          predicates:
            - Path=/NonFunctionalMessage/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


